apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-k8s
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/craigedmunds/argocd-eda.git
      revision: HEAD
      directories:
      - path: local-k8s/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "eventing"
      source:
        repoURL: https://github.com/craigedmunds/argocd-eda.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true