apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: eventing
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 78.0.0
    # helm:
    #   releaseName: sealed-secrets
    helm:
      parameters:
        - name: thanosRuler.service.enabled
          value: 'false'
        - name: alertmanager.enabled
          value: 'false'
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
